## Pandas 사용
- 두가지 데이터 타입 
    - Series : index & value로 구성
    - Dataframe : index, column, value로 구성

**지금부터는 여러분도 같이 타이핑하면서 따라오시면 좋겠습니다**

In [1]:
!pip install pandas numpy 

^C


In [3]:
import numpy as np #행렬연산에 사용함. 선형대수학에서 쓰는 과학자들이 많이 쓰는 라이브러리
np.random.random(10) #랜덤 메소드 

array([0.5202303 , 0.54555345, 0.07598444, 0.59979277, 0.92989443,
       0.2958143 , 0.16839244, 0.97523329, 0.34050096, 0.64863879])

In [2]:
# series
import pandas as pd
import numpy as np

mySeries = pd.Series(np.random.random(10)) #시리즈=인덱스, 밸류로 구성 
mySeries

0    0.227660
1    0.789587
2    0.436571
3    0.666474
4    0.961827
5    0.616586
6    0.880177
7    0.234248
8    0.471459
9    0.344608
dtype: float64

In [3]:
# 잠시 numpy

# 행렬
np.array([1,2,3]) #자기들끼리 연산이 가능하다는 점이 리스트와 차이가 있따!

array([1, 2, 3])

In [4]:
myArray = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

myArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# 행렬연산도 가능하다
myArray @ myArray

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [6]:
myArray.shape

(3, 3)

In [8]:
# 다시 pandas로 돌아온다.
mySeries = pd.Series(
          data = ['apple', 'banana', 'kiwi'], 
          index=['a', 'b', 'c'])

In [7]:
mySeries

a     apple
b    banana
c      kiwi
dtype: object

In [7]:
mySeries.values, mySeries.index #판다스는 넘파이를 가지고 있다. 시리즈에서도 인덱싱이 가능하다. 

(array(['apple', 'banana', 'kiwi'], dtype=object),
 Index(['a', 'b', 'c'], dtype='object'))

In [9]:
mySeries['c']

'kiwi'

In [9]:
# 배열의 값을 바꿀수 있다.

mySeries['a'] = 'peach'
mySeries

a     peach
b    banana
c      kiwi
dtype: object

In [10]:
# 배열을 추가할 수 있다.

mySeries['d'] = "apple"
mySeries

a     peach
b    banana
c      kiwi
d     apple
dtype: object

In [11]:
# 브로드캐스팅도 가능하다 #브로드캐스팅이란? 연산식이 모든 요소에 적용되는 것을 말한다!

mySeries * 2

a      peachpeach
b    bananabanana
c        kiwikiwi
d      appleapple
dtype: object

In [13]:
mySeries['b':'c']

b    banana
c      kiwi
dtype: object

In [12]:
mySeries[:'c']

a     peach
b    banana
c      kiwi
dtype: object

In [14]:
# 두칸씩 점프해서 보여줄수도 있다.

mySeries[::2]

a    peach
c     kiwi
dtype: object

In [24]:
# 딕셔너리로 데이터를 선언할 수도 있다. 

mySeries2 = pd.Series({'d' : 'peach',
           'e' : 'tomato',
           'f' : 'kiwi'})
mySeries2

d     peach
e    tomato
f      kiwi
dtype: object

In [25]:
mySeries

a     peach
b    banana
c      kiwi
d     apple
dtype: object

In [26]:
mySeries2

d     peach
e    tomato
f      kiwi
dtype: object

In [28]:
# NaN은 오류값, None과 비슷하다

result = mySeries + mySeries2 #덧셈을 할 때 브로드캐스팅이 일어났고, 인덱스 기준으로 움직임. 
result

a           NaN
b           NaN
c           NaN
d    applepeach
e           NaN
f           NaN
dtype: object

In [29]:
# isnull 메서드로 null값만 필터할 수 있다.
result.isnull()

a     True
b     True
c     True
d    False
e     True
f     True
dtype: bool

In [30]:
# masking
result[result.isnull()] = mySeries
result

a         peach
b        banana
c          kiwi
d    applepeach
e           NaN
f           NaN
dtype: object

In [31]:
result[~result.isnull()] = mySeries2
result

a      NaN
b      NaN
c      NaN
d    peach
e      NaN
f      NaN
dtype: object

### Dataframe에 대해서 알아봅시다.
- 리스트 안에 딕셔너리
- 딕셔너리 안에 리스트

데이터프레임 = 시리즈가 여러 개 있음. 인덱스, 컬럼, 밸류
시리즈 선언 = 딕셔너리 or 리스트 선언

In [35]:
myDataframe = pd.DataFrame([
    {"name" : "easy", "email" : "easy@easy.com"},
    {"name" : "data", "email" : "data@naver.com"},
    {"name" : "science", "email" : "science@gmail.com"}
])

myDataframe

name              email
0     easy      easy@easy.com
1     data     data@naver.com
2  science  science@gmail.com

In [36]:
# 딕셔너리 안에 리스트

myDataframe = pd.DataFrame({
    "name" : ["easy", "data", "science"],
    "email" : ["easy@easy.com", "data@naver.com", "science@gmail.com"]
})
myDataframe

name              email
0     easy      easy@easy.com
1     data     data@naver.com
2  science  science@gmail.com

In [37]:
# 인덱스를 추가할 수도 있다.
myDataframe = pd.DataFrame({
    "name" : ["easy", "data", "science"],
    "email" : ["easy@easy.com", "data@naver.com", "science@gmail.com"]
}, index=['a','b','c'])

myDataframe

name              email
a     easy      easy@easy.com
b     data     data@naver.com
c  science  science@gmail.com

In [43]:
# 다음과 같이 바꿀 수도 있다. 

myDataframe.index = 0,1,2
myDataframe

name              email
0     easy      easy@easy.com
1     data     data@naver.com
2  science  science@gmail.com

In [38]:
myDataframe.columns, myDataframe.values 

(Index(['name', 'email'], dtype='object'),
 array([['easy', 'easy@easy.com'],
        ['data', 'data@naver.com'],
        ['science', 'science@gmail.com']], dtype=object))

In [39]:
myDataframe.index

Index(['a', 'b', 'c'], dtype='object')

In [40]:
myDataframe

name              email
a     easy      easy@easy.com
b     data     data@naver.com
c  science  science@gmail.com

In [44]:
# row 선택 : loc #데이터프레임에 인덱싱 

myDataframe.loc[1]

name               data
email    data@naver.com
Name: 1, dtype: object

In [45]:
myDataframe.loc[1]['name']

'data'

In [46]:
# column 선택 : 컬럼 이름으로 인덱싱
myDataframe['email'][1]

'data@naver.com'

In [47]:
myDataframe.iloc[1]

name               data
email    data@naver.com
Name: 1, dtype: object

In [50]:
# 행추가 #loc를 추가할 수 있음

myDataframe.loc[3] = {'name' : 'gangnam', "email" : 'gangnam@gmail.com'}
myDataframe

name              email
0     easy      easy@easy.com
1     data     data@naver.com
2  science  science@gmail.com
3  gangnam  gangnam@gmail.com

In [51]:
# 기존 데이터를 변형해서 print 할 수 있다. 순서를 바꿔서 볼 수 있음

myDataframe.loc[0:2, ["email", 'name']] 

email     name
0      easy@easy.com     easy
1     data@naver.com     data
2  science@gmail.com  science

In [30]:
# 데이터 타입을 볼 수도 있다. (문자열/실수/정수)
myDataframe.dtypes

name     object
email    object
dtype: object

In [54]:
# 상위 행들만 관찰
myDataframe.head(2)

name           email
0  easy   easy@easy.com
1  data  data@naver.com

In [56]:
# 하위 행들만 관찰
myDataframe.tail(2)

name              email
2  science  science@gmail.com
3  gangnam  gangnam@gmail.com

In [61]:
# 기능들에 대해서 배워보자.
# apply, concat, groupby, merge
import random
#랜덤값을 고정하고 싶으면 랜덤시드를 붙이면 됨

def create_random_table(num_rows) :
    """
    랜덤한 테이블을 만드는 함수
    num_rows : 원하는 행의 갯수를 입력하라.
    """
    fruits = ['apple', 'banana', 'kiwi', 'orange', 'tomato', 'mango', 'strawberry']
    emails = ['gmail.com', 'naver.com', 'outlook.com']

    my_rows = []
    for _ in range(num_rows) :
        fruit = random.choice(fruits)
        email = random.choice(emails)
        my_rows.append({"name" : fruit, "email" : f"{fruit}@{email}"})
    return my_rows

df = create_random_table(3)
df = pd.DataFrame(df)
df

name               email
0  tomato  tomato@outlook.com
1    kiwi    kiwi@outlook.com
2  orange  orange@outlook.com

In [66]:
# apply : 함수를 적용해준다. 특정 칼럼에 반복되는 연산을 일괄적으로 적용해줌
# domain을 뽑아봅시다. 

def extract_domain(email) :
    domain = email.split("@")[1]
    domain = domain.replace(".com", "")
    return domain

df['email'].apply(extract_domain)

0    outlook
1    outlook
2    outlook
Name: email, dtype: object

In [65]:
# lambda를 이용해서 추출할 수도 있다. 람다=이름 없는 함수

df['domain'] = df['email'].apply(lambda x : x.split("@")[1].replace(".com",""))
df

name               email   domain
0  tomato  tomato@outlook.com  outlook
1    kiwi    kiwi@outlook.com  outlook
2  orange  orange@outlook.com  outlook

In [74]:
df2 = create_random_table(8)
df2 = pd.DataFrame(df2)
df2

name                   email
0       mango         mango@naver.com
1      banana        banana@naver.com
2       mango         mango@naver.com
3  strawberry  strawberry@outlook.com
4      banana        banana@gmail.com
5      orange        orange@naver.com
6       apple         apple@naver.com
7      banana        banana@naver.com

In [83]:
# concat : 데이터를 이어 붙일 때 사용 (위아래로 붙이거나 양옆으로 붙일 때)

pd.concat([df, df2], axis=0).reset_index(drop=True) #원래 df에만 도메인이 있기 떄문에 나중에 붙인 df2에는 오류
# axis = 1은 가로로 붙인다. 수직으로 붙이면 0, 수평은 1

name                   email   domain
0       tomato      tomato@outlook.com  outlook
1         kiwi        kiwi@outlook.com  outlook
2       orange      orange@outlook.com  outlook
3        mango         mango@naver.com      NaN
4       banana        banana@naver.com      NaN
5        mango         mango@naver.com      NaN
6   strawberry  strawberry@outlook.com      NaN
7       banana        banana@gmail.com      NaN
8       orange        orange@naver.com      NaN
9        apple         apple@naver.com      NaN
10      banana        banana@naver.com      NaN

In [84]:
# value 값을 바탕으로 sorting도 진행할 수 있다. 

df2.sort_values(by="name") 

name                   email
6       apple         apple@naver.com
1      banana        banana@naver.com
4      banana        banana@gmail.com
7      banana        banana@naver.com
0       mango         mango@naver.com
2       mango         mango@naver.com
5      orange        orange@naver.com
3  strawberry  strawberry@outlook.com

In [85]:
# Merge에 대해서
# 공유하는 키 값이 존재하는 데이터를 합칠 때 사용

cars = pd.DataFrame([
    {"name" : "ramborgini", "color" : "red", "engine" : "v12", "displacement" : 4000},
    {"name" : "audiA4" , "color" : "black", "engine" : "v6", "displacement" : 2000},
    {"name" : "benz", "color" : "blue", "engine" : "turbo disel", "displacement" : 2000}
])
cars

name  color       engine  displacement
0  ramborgini    red          v12          4000
1      audiA4  black           v6          2000
2        benz   blue  turbo disel          2000

In [88]:
driver = pd.DataFrame([
    {"driver" : "Juliani" , "age" : 36, "name" : "ramborgini"},
    {"driver" : "Ahmer" , "age" : 40, "name" : "ramborgini"},
    {"driver" : "Boruto" , "age" : 50, "name" : "benz"},
    {"driver" : "Panda" , "age" : 45, "name" : "audiA4"},
    {"driver" : "Bear", "age" : 33, "name" : "lexus"}
])

driver

driver  age        name
0  Juliani   36  ramborgini
1    Ahmer   40  ramborgini
2   Boruto   50        benz
3    Panda   45      audiA4
4     Bear   33       lexus

In [89]:
# 값들을 sorting 해줄수도 있다.

driver.sort_values(by='age')

driver  age        name
4     Bear   33       lexus
0  Juliani   36  ramborgini
1    Ahmer   40  ramborgini
3    Panda   45      audiA4
2   Boruto   50        benz

In [91]:
# name이 같을 때, 데이터들을 merge 해보자 #키값 name에 맞춰

pd.merge(driver, cars, on='name')

driver  age        name  color       engine  displacement
0  Juliani   36  ramborgini    red          v12          4000
1    Ahmer   40  ramborgini    red          v12          4000
2   Boruto   50        benz   blue  turbo disel          2000
3    Panda   45      audiA4  black           v6          2000

In [94]:
# merge를 하는 방식은 
# left : 왼쪽에 있는 것들에 merge
# right : 오른쪽에 있는 것들에 merge
# outer : 합집합으로 merge 전체 다. 일치하고 아니고 떠나서
# inner : 교집합으로 merge 일치하는 키값만 있는 것

pd.merge(cars, driver, on='name', how='outer') #how를 넣지 않으면 inner로 출력

name  color       engine  displacement   driver  age
0  ramborgini    red          v12        4000.0  Juliani   36
1  ramborgini    red          v12        4000.0    Ahmer   40
2      audiA4  black           v6        2000.0    Panda   45
3        benz   blue  turbo disel        2000.0   Boruto   50
4       lexus    NaN          NaN           NaN     Bear   33

In [95]:
# groupby에 대해서 배워보자

df = pd.DataFrame([
    {"name" : "easy", "age" : 30, "level" : "A"},
    {"name" : "data", "age" : 28, "level" : "B"},
    {"name" : "science", "age" : 31, "level" : "B"},
    {"name" : "bob", "age": 40, "level" : "C" },
    {"name" : "henry", "age" : 38, "level" : "B"}

])

df

name  age level
0     easy   30     A
1     data   28     B
2  science   31     B
3      bob   40     C
4    henry   38     B

In [96]:
df.groupby("level")['age'].mean() #집계함수

level
A    30.000000
B    32.333333
C    40.000000
Name: age, dtype: float64

In [98]:
df.groupby("level")['name'].count() #서수도 가능.

level
A    1
B    3
C    1
Name: name, dtype: int64

In [100]:
df.describe() #통계변수 = 1. 연속형 변수(나이, 체중, 키 등 평균, 중위, 분산, 표준편차을 계량할 수 있는 것) 2. 이산형 변수 (젠더, 차 종류, 거주지=빈도수와 비율로 표현) 평균을 비교할 때는 티 테스트를 씀. 이산형은 카이제곱검정. 

age
count   5.000000
mean   33.400000
std     5.272571
min    28.000000
25%    30.000000
50%    31.000000
75%    38.000000
max    40.000000

In [101]:
# pivot table
# 1. pivot table은 데이터를 원하는 모양으로 변경해주는 방법 
# 2. pivot과 pivot_table이 있다.

In [58]:
df.head()

name  age level
0     easy   30     A
1     data   28     B
2  science   31     B
3      bob   40     C
4    henry   38     B

In [102]:
# 새로운 데이터인 weight를 정의

df['weight'] = np.random.randint(50,100,len(df))

In [103]:
df['gender'] = np.random.choice(['M','F'], len(df))

In [61]:
df

name  age level  weight gender
0     easy   30     A      58      M
1     data   28     B      68      F
2  science   31     B      70      M
3      bob   40     C      93      F
4    henry   38     B      84      F

In [105]:
# 데이터 재포맷팅

df = df[['name', 'gender', 'level', 'weight']]
df

name gender level  weight
0     easy      F     A      66
1     data      M     B      75
2  science      F     B      57
3      bob      F     C      95
4    henry      F     B      74

In [109]:
df.pivot(index='gender', columns='name')

level                         weight                          
name     bob data easy henry science    bob  data  easy henry science
gender                                                               
F          C  NaN    A     B       B   95.0   NaN  66.0  74.0    57.0
M        NaN    B  NaN   NaN     NaN    NaN  75.0   NaN   NaN     NaN

In [110]:
# index, columns, values로 input을 넣어준다.

df1 = df.pivot(index="gender", columns = "name", values='weight')
df1

name     bob  data  easy  henry  science
gender                                  
F       95.0   NaN  66.0   74.0     57.0
M        NaN  75.0   NaN    NaN      NaN

In [111]:
# 에러가 발생한다. 같은 셀에 중복값이 있기 떄문에

df.pivot(index='gender', columns='level', values='weight')

ValueError: Index contains duplicate entries, cannot reshape

In [113]:
# pivot은 기존 데이터의 변형이 일어나지 않는다.
# pivot_table은 중복된 값이 있을때도 처리를 해줄 수 있다.
# 기존 데이터에 더불어 새로운 집계를 해야하는 경우.
# 집계될 때 평균값으로 집계됨을 볼 수 있다. 

df.pivot_table(index='gender', columns='level', values='weight', aggfunc='mean') #에그펑크=집계 메소드. 데이터를 집계하고 분석하는 데 유용한 메소드

level      A     B     C
gender                  
F       66.0  65.5  95.0
M        NaN  75.0   NaN